// tslint:disable
// eslint-disable
/**
 * CoopCare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Intervention
 */
export interface Intervention {
    /**
     * 
     * @type {string}
     * @memberof Intervention
     */
    categoryId: string;
    /**
     * 
     * @type {string}
     * @memberof Intervention
     */
    targetId: string;
    /**
     * 
     * @type {string}
     * @memberof Intervention
     */
    description: string;
}

export function InterventionFromJSON(json: any): Intervention {
    return InterventionFromJSONTyped(json, false);
}

export function InterventionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Intervention {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'targetId': json['targetId'],
        'description': json['description'],
    };
}

export function InterventionToJSON(value?: Intervention | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categoryId': value.categoryId,
        'targetId': value.targetId,
        'description': value.description,
    };
}


