// tslint:disable
// eslint-disable
/**
 * CoopCare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OmahaProblemDomain
 */
export interface OmahaProblemDomain {
    /**
     * 
     * @type {string}
     * @memberof OmahaProblemDomain
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaProblemDomain
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaProblemDomain
     */
    description: string;
}

export function OmahaProblemDomainFromJSON(json: any): OmahaProblemDomain {
    return OmahaProblemDomainFromJSONTyped(json, false);
}

export function OmahaProblemDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmahaProblemDomain {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
    };
}

export function OmahaProblemDomainToJSON(value?: OmahaProblemDomain | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
    };
}


