// tslint:disable
// eslint-disable
/**
 * CoopCare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OmahaProblem
 */
export interface OmahaProblem {
    /**
     * 
     * @type {string}
     * @memberof OmahaProblem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaProblem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaProblem
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaProblem
     */
    domainId: string;
}

export function OmahaProblemFromJSON(json: any): OmahaProblem {
    return OmahaProblemFromJSONTyped(json, false);
}

export function OmahaProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmahaProblem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'domainId': json['domainId'],
    };
}

export function OmahaProblemToJSON(value?: OmahaProblem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'domainId': value.domainId,
    };
}


