// tslint:disable
// eslint-disable
/**
 * CoopCare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OmahaInterventionCategory
 */
export interface OmahaInterventionCategory {
    /**
     * 
     * @type {string}
     * @memberof OmahaInterventionCategory
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaInterventionCategory
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaInterventionCategory
     */
    description: string;
}

export function OmahaInterventionCategoryFromJSON(json: any): OmahaInterventionCategory {
    return OmahaInterventionCategoryFromJSONTyped(json, false);
}

export function OmahaInterventionCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmahaInterventionCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
    };
}

export function OmahaInterventionCategoryToJSON(value?: OmahaInterventionCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
    };
}


