// tslint:disable
// eslint-disable
/**
 * CoopCare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OmahaSymptom
 */
export interface OmahaSymptom {
    /**
     * 
     * @type {string}
     * @memberof OmahaSymptom
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaSymptom
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaSymptom
     */
    domainId: string;
    /**
     * 
     * @type {string}
     * @memberof OmahaSymptom
     */
    problemId: string;
}

export function OmahaSymptomFromJSON(json: any): OmahaSymptom {
    return OmahaSymptomFromJSONTyped(json, false);
}

export function OmahaSymptomFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmahaSymptom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'domainId': json['domainId'],
        'problemId': json['problemId'],
    };
}

export function OmahaSymptomToJSON(value?: OmahaSymptom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'domainId': value.domainId,
        'problemId': value.problemId,
    };
}


