// tslint:disable
// eslint-disable
/**
 * CoopCare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProblemTypeModifier {
    HealthPromotion = 'health-promotion',
    Potential = 'potential',
    Actual = 'actual'
}

export function ProblemTypeModifierFromJSON(json: any): ProblemTypeModifier {
    return ProblemTypeModifierFromJSONTyped(json, false);
}

export function ProblemTypeModifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemTypeModifier {
    return json as ProblemTypeModifier;
}

export function ProblemTypeModifierToJSON(value?: ProblemTypeModifier | null): any {
    return value as any;
}

