// tslint:disable
// eslint-disable
/**
 * CoopCare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProblemDomainModifier {
    Individual = 'individual',
    Family = 'family',
    Community = 'community'
}

export function ProblemDomainModifierFromJSON(json: any): ProblemDomainModifier {
    return ProblemDomainModifierFromJSONTyped(json, false);
}

export function ProblemDomainModifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDomainModifier {
    return json as ProblemDomainModifier;
}

export function ProblemDomainModifierToJSON(value?: ProblemDomainModifier | null): any {
    return value as any;
}

